### ISSUE TITLE
subiquity python bits not installed in python path

### ISSUE THREAD

**Issue by raharper** [CanonicalLtd/subiquity-deb#2]
```
ubuntu@w1:~$ /usr/bin/subiquity --help
Traceback (most recent call last):
  File "/usr/bin/subiquity", line 20, in <module>
    from subiquity.log import setup_logger
ImportError: No module named 'subiquity'
```

**Comment by raharper** [comment]
$ dpkg -L subiquity  | grep tui
/usr/share/subiquity/bin/subiquity-tui
ubuntu@w1:~$ /usr/share/subiquity/bin/subiquity-tui 
Traceback (most recent call last):
  File "/usr/share/subiquity/bin/subiquity-tui", line 20, in <module>
    from subiquity.log import setup_logger
ImportError: No module named 'subiquity'

**Comment by adam-stokes** [comment]
ah weird, its installed in both places on my setup:

```
‹master› »»»» dpkg -L subiquity|grep subiquity-tui                                                                          0|14:03:09
/usr/share/subiquity/bin/subiquity-tui
/usr/share/subiquity/subiquity-tui

```

**Comment by adam-stokes** [comment]
Should be fixed now
